config/routes.rb
Project2::Application.routes.draw do
  root  'static_pages#home'
  match '/blog',    to: 'static_pages#blog',    via: 'get'
  match '/faq',    to: 'static_pages#faq',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def faq
  end

  def about
  end

  def blog
  end

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Bob Loblaw's Law Blog"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    by Jackson and 
    <a href="https://www.facebook.com/chelsey.denton.7/">Chelsey</a>
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Bob Loblaw's Law Blog", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "About",    about_path %></li>
          <li><%= link_to "Blog",    blog_path %></li>
          <li><%= link_to "FAQ", faq_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Chelsey and Jackson</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/blog.html.erb
<% provide(:title, 'Blog') %>
<h1>Blog</h1>
<p>Find me in app/views/static_pages/blog.html.erb</p>

app/views/static_pages/faq.html.erb
<% provide(:title, 'FAQ') %>
<h1>Frequently Asked Questions</h1>
<p>Find me in app/views/static_pages/faq.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<h1>spaccccccce</h1>
<p>:)</p>